# Generated by Django 2.1.4 on 2018-12-27 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hirer',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('nick_name', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=255)),
                ('lock', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 12, 27, 11, 48, 1, 659518))),
                ('last_time', models.DateTimeField(null=True)),
                ('last_ip', models.CharField(max_length=15)),
                ('login_time', models.DateTimeField(null=datetime.datetime(2018, 12, 27, 11, 48, 1, 659579))),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='modelfile.User'),
        ),
        migrations.AddField(
            model_name='hirer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hirer', to='modelfile.User'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='modelfile.User'),
        ),
    ]
