# Generated by Django 2.1.4 on 2018-12-27 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 12, 9, 16, 211555)),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(null=datetime.datetime(2018, 12, 27, 12, 9, 16, 211623)),
        ),
    ]
