# Generated by Django 2.1.4 on 2018-12-27 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelfile', '0002_auto_20181227_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='modelfile.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 12, 24, 56, 249706)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
    ]
